name: github-action-section3-practice
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # or npm install
      - name: Lint
        run: npm lint
      - name: Print something
        run: echo "Done linting"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # or npm install
      - name: Test
        run: npm test
      - name: Print something
        run: echo "Done testing"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # or npm install
      - name: Build
        run: npm run build
      - name: Print something
        run: echo "Done!!!"